# Generated by Django 2.2.5 on 2019-10-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20191011_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenitiy',
            new_name='Amenity',
        ),
    ]
