# Generated by Django 2.2.5 on 2020-01-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20191015_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(),
        ),
    ]
